//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MES.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加物料.
        /// </summary>
        internal static string AddMateriel {
            get {
                return ResourceManager.GetString("AddMateriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加产品.
        /// </summary>
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --全部--.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件无法保存，请确认文件不是只读状态并且未被打开.
        /// </summary>
        internal static string CannotSave {
            get {
                return ResourceManager.GetString("CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分类.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改数量.
        /// </summary>
        internal static string ChangeQuantity {
            get {
                return ResourceManager.GetString("ChangeQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代码.
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据已更改，是否保存？.
        /// </summary>
        internal static string DataChangedSaveSuccess {
            get {
                return ResourceManager.GetString("DataChangedSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel 97-2003 工作簿|*.xls|Excel 工作簿|*.xlsx|PDF|*.pdf|CSV (逗号分隔)|*.csv.
        /// </summary>
        internal static string ExcelFile {
            get {
                return ResourceManager.GetString("ExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入库完成.
        /// </summary>
        internal static string FinishInbound {
            get {
                return ResourceManager.GetString("FinishInbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完工.
        /// </summary>
        internal static string FinishJob {
            get {
                return ResourceManager.GetString("FinishJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功是否关闭编辑界面？.
        /// </summary>
        internal static string IsCloseAfterSaveSuccess {
            get {
                return ResourceManager.GetString("IsCloseAfterSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 型号.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名/密码错误.
        /// </summary>
        internal static string NameOrPasswordError {
            get {
                return ResourceManager.GetString("NameOrPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入的新密码不一致.
        /// </summary>
        internal static string NewPasswordAgain {
            get {
                return ResourceManager.GetString("NewPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入新密码长度太短.
        /// </summary>
        internal static string NewPasswordTooShort {
            get {
                return ResourceManager.GetString("NewPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码输入错误.
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择工序.
        /// </summary>
        internal static string PleaseSelectProcess {
            get {
                return ResourceManager.GetString("PleaseSelectProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入正确的成品条码.
        /// </summary>
        internal static string PlsInputProductCode {
            get {
                return ResourceManager.GetString("PlsInputProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入正确的产品跟踪码.
        /// </summary>
        internal static string PlsInputProductTraceCode {
            get {
                return ResourceManager.GetString("PlsInputProductTraceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择.
        /// </summary>
        internal static string plsSelect {
            get {
                return ResourceManager.GetString("plsSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印物料.
        /// </summary>
        internal static string PrintMateriel {
            get {
                return ResourceManager.GetString("PrintMateriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产产线.
        /// </summary>
        internal static string ProductLine {
            get {
                return ResourceManager.GetString("ProductLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关联领料单号.
        /// </summary>
        internal static string RelaMaterialOrder {
            get {
                return ResourceManager.GetString("RelaMaterialOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关联出库单号.
        /// </summary>
        internal static string RelaOutbound {
            get {
                return ResourceManager.GetString("RelaOutbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关联工单号.
        /// </summary>
        internal static string RelaProductionOrder {
            get {
                return ResourceManager.GetString("RelaProductionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关联生产计划.
        /// </summary>
        internal static string RelaProductionPlan {
            get {
                return ResourceManager.GetString("RelaProductionPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关联采购申请单.
        /// </summary>
        internal static string RelaPurchaseOrder {
            get {
                return ResourceManager.GetString("RelaPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关联销售单.
        /// </summary>
        internal static string RelaSalesOrder {
            get {
                return ResourceManager.GetString("RelaSalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功.
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功，是否打开.
        /// </summary>
        internal static string SaveSuccessOpenIt {
            get {
                return ResourceManager.GetString("SaveSuccessOpenIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功是否关闭编辑界面？.
        /// </summary>
        internal static string SaveSuccessQuestion {
            get {
                return ResourceManager.GetString("SaveSuccessQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描物料.
        /// </summary>
        internal static string ScanMateriel {
            get {
                return ResourceManager.GetString("ScanMateriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 规格.
        /// </summary>
        internal static string Spec {
            get {
                return ResourceManager.GetString("Spec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户编号.
        /// </summary>
        internal static string UserCode {
            get {
                return ResourceManager.GetString("UserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供应商.
        /// </summary>
        internal static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本：.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
