//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6400
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.6400.
// 
namespace Wms.Mobile.SmartDeviceService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using Business.Domain.Mobile.Mobile;
    using Business.Domain.Mobile.Inventory;

    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SmartDeviceSoap", Namespace="http://tempuri.org/")]
    public partial class SmartDevice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SmartDevice() {
            this.Url = "http://localhost/Wms/Service/SmartDevice.asmx";
        }

        /// <remarks/>
        public SmartDevice(string url)
        {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadReceivingTaskResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadReceivingTaskResult(ReceivingTaskResult result) {
            object[] results = this.Invoke("UploadReceivingTaskResult", new object[] {
                        result});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUploadReceivingTaskResult(ReceivingTaskResult result, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UploadReceivingTaskResult", new object[] {
                        result}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndUploadReceivingTaskResult(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadPutawayTaskResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadPutawayTaskResult(PutawayTaskResult result) {
            object[] results = this.Invoke("UploadPutawayTaskResult", new object[] {
                        result});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUploadPutawayTaskResult(PutawayTaskResult result, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UploadPutawayTaskResult", new object[] {
                        result}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndUploadPutawayTaskResult(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadPickTaskResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadPickTaskResult(PickTaskResult result) {
            object[] results = this.Invoke("UploadPickTaskResult", new object[] {
                        result});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUploadPickTaskResult(PickTaskResult result, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UploadPickTaskResult", new object[] {
                        result}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndUploadPickTaskResult(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateDeliveryTask", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateDeliveryTask(OutboundBill outboundBill) {
            object[] results = this.Invoke("UpdateDeliveryTask", new object[] {
                        outboundBill});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateDeliveryTask(OutboundBill outboundBill, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateDeliveryTask", new object[] {
                        outboundBill}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndUpdateDeliveryTask(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
}
